# slug -> doğru Türkçe keyword eşlemesi (sadece bozuk olanlar)
FIX = {
'agac':'ağaç','aglama':'ağlama','altin':'altın','ates':'ateş','ayi':'ayı',
'balik':'balık','baykus':'baykuş','beyin':'beyin','bicak':'bıçak','bocek':'böcek',
'bogulmak':'boğulmak','bosanma':'boşanma','bosluk':'boşluk','bugday':'buğday',
'cocuk':'çocuk','cuzdan':'cüzdan','dag':'dağ','dis':'diş','dogum':'doğum',
'dugun':'düğün','dovusmek':'dövüşmek','dukkan':'dükkan','dusman':'düşman',
'es':'eş','esek':'eşek','fotograf':'fotoğraf','findik':'fındık','firtina':'fırtına',
'gec-kalmak':'geç kalmak','gulmek':'gülmek','gokdelen':'gökdelen','gokkusagi':'gökkuşağı',
'gokyuzu':'gökyüzü','gol':'göl','gomlek':'gömlek','goz':'göz','gul':'gül',
'gumus':'gümüş','gunes':'güneş','guvercin':'güvercin','hali':'halı','hastalik':'hastalık',
'havaalani':'havaalanı','hirsiz':'hırsız','hirsizlik':'hırsızlık','is-bulmak':'iş bulmak',
'kabe':'Kâbe','kapi':'kapı','kaplumbaga':'kaplumbağa','karanlik':'karanlık','kardes':'kardeş',
'karinca':'karınca','kacmak':'kaçmak','keci':'keçi','komsu':'komşu','kopek':'köpek',
'kosmak':'koşmak','kurbaga':'kurbağa','kus':'kuş','kupe':'küpe','kilic':'kılıç',
'kirmizi':'kırmızı','magara':'mağara','mezarlik':'mezarlık','mucevher':'mücevher',
'nisan':'nişan','olum':'ölüm','oruc':'oruç','otobus':'otobüs','papagan':'papağan',
'pirinc':'pirinç','pinar':'pınar','ruzgar':'rüzgar','sac':'saç','sahin':'şahin',
'sari':'sarı','sarilmak':'sarılmak','sarimsak':'sarımsak','savas':'savaş','sevinc':'sevinç',
'sican':'sıçan','sigircik':'sığırcık','sinav':'sınav','sogan':'soğan','sut':'süt',
'tas':'taş','tavsan':'tavşan','tirmanmak':'tırmanmak','tirnak':'tırnak','ucak':'uçak',
'ucmak':'uçmak','ucurum':'uçurum','volkan':'volkan','yagmur':'yağmur','yangin':'yangın',
'yilan':'yılan','yildiz':'yıldız','yon-bulamamak':'yön bulamamak','yukseklik':'yükseklik',
'yuz':'yüz','yuzmek':'yüzmek','yuzuk':'yüzük','cadir':'çadır','calismak':'çalışmak',
'camur':'çamur','canta':'çanta','carsi':'çarşı','cati':'çatı','cay':'çay',
'cikolata':'çikolata','cimen':'çimen','cicek':'çiçek','corap':'çorap','col':'çöl',
'ciplaklik':'çıplaklık','okuz':'öküz','olmek':'ölmek','olu':'ölü','opmek':'öpmek',
'ordek':'ördek','orumcek':'örümcek','ozgur-kalmak':'özgür kalmak','uzum':'üzüm',
'sapka':'şapka','sarap':'şarap','seker':'şeker','selale':'şelale','semsiye':'şemsiye',
'seytan':'şeytan','simsek':'şimşek','abdest':'abdest','abi':'abi','abla':'abla',
'akrep':'akrep','anahtar':'anahtar','anne':'anne','araba':'araba','arkadas':'arkadaş',
'asansor':'asansör','aslan':'aslan','ayak':'ayak','ayakkabi':'ayakkabı','aydinlik':'aydınlık',
'bahce':'bahçe','baris':'barış','barismak':'barışmak','bina':'bina','bodrum':'bodrum',
'burun':'burun','damat':'damat','deve':'deve','dil':'dil','duman':'duman','duvar':'duvar',
'ekin':'ekin','fabrika':'fabrika','fare':'fare','fasulye':'fasulye','fener':'fener',
'fil':'fil','gazete':'gazete','gelin':'gelin','gemi':'gemi','geyik':'geyik','gri':'gri',
'hac':'hac','hakim':'hâkim','horoz':'horoz','hurma':'hurma','ikiz':'ikiz','incir':'incir',
'inek':'inek','istasyon':'istasyon','kale':'kale','kalem':'kalem','kalp':'kalp','kan':'kan',
'kaplan':'kaplan','kar':'kar','karga':'karga','karpuz':'karpuz','kartal':'kartal',
'kavga':'kavga','kaya':'kaya','kaz':'kaz','kedi':'kedi','kek':'kek','kelebek':'kelebek',
'kemik':'kemik','kilise':'kilise','kilit':'kilit','kitap':'kitap','kolye':'kolye',
'korku':'korku','koyun':'koyun','kulak':'kulak','kule':'kule','kum':'kum','kurt':'kurt',
'kuyu':'kuyu','kuzu':'kuzu','lamba':'lamba','leylek':'leylek','makas':'makas','masa':'masa',
'mavi':'mavi','maymun':'maymun','mektup':'mektup','melek':'melek','merdiven':'merdiven',
'mescit':'mescit','meyve':'meyve','mezar':'mezar','misafir':'misafir','mont':'mont',
'mor':'mor','motosiklet':'motosiklet','mum':'mum','mutfak':'mutfak','namaz':'namaz',
'nar':'nar','nehir':'nehir','nikah':'nikâh','nur':'nur','oda':'oda','ok':'ok','okul':'okul',
'orman':'orman','otel':'otel','palto':'palto','pantolon':'pantolon','para':'para',
'parmak':'parmak','pasta':'pasta','patates':'patates','pazar':'pazar','pembe':'pembe',
'pencere':'pencere','perde':'perde','peygamber':'peygamber','peynir':'peynir','polis':'polis',
'portakal':'portakal','saat':'saat','saklanmak':'saklanmak','sandalye':'sandalye',
'saray':'saray','secde':'secde','sel':'sel','sevgili':'sevgili','silah':'silah','sinek':'sinek',
'sis':'sis','siyah':'siyah','sokak':'sokak','su':'su','tabanca':'tabanca','tavuk':'tavuk',
'tekne':'tekne','telefon':'telefon','televizyon':'televizyon','tepe':'tepe','tilki':'tilki',
'timsah':'timsah','tohum':'tohum','toprak':'toprak','tren':'tren','turuncu':'turuncu',
'tuvalet':'tuvalet','tuz':'tuz','yakalanmak':'yakalanmak','yanmak':'yanmak','yaprak':'yaprak',
'yara':'yara','yarasa':'yarasa','yatak':'yatak','yelkenli':'yelkenli','yumurta':'yumurta',
'yunus':'yunus','yol':'yol','yolculuk':'yolculuk','zeytin':'zeytin','zombi':'zombi',
'ada':'ada','at':'at','ay':'ay','bal':'bal','baba':'baba','banyo':'banyo','bebek':'bebek',
'beyaz':'beyaz','bilezik':'bilezik','bilgisayar':'bilgisayar','bisiklet':'bisiklet',
'bulut':'bulut','buz':'buz','cami':'cami','canavar':'canavar','cehennem':'cehennem',
'ceket':'ceket','cennet':'cennet','ceviz':'ceviz','ceylan':'ceylan','cin':'cin','civciv':'civciv',
'deniz':'deniz','deprem':'deprem','derinlik':'derinlik','dev':'dev','dolunay':'dolunay',
'domates':'domates','domuz':'domuz','dua':'dua','ekmek':'ekmek','el':'el','elbise':'elbise',
'eldiven':'eldiven','elma':'elma','et':'et','etek':'etek','ev':'ev','evlilik':'evlilik',
'ezan':'ezan','gelinlik':'gelinlik','hamilelik':'hamilelik','hapishane':'hapishane',
'hapsedilmek':'hapsedilmek','hastane':'hastane','hayalet':'hayalet','kabus':'kabus',
'kahve':'kahve','kaybolmak':'kaybolmak','kovalanmak':'kovalanmak','mavi':'mavi',
'nisan':'nişan','pirinc':'pirinç','sac':'saç',
'uckmak-dusmek':'düşmek','dusmek':'düşmek','bebek-aglamasi':'ağlayan bebek','para-bulmak':'para bulmak',
'olu':'ölü','yagmur':'yağmur','yilan':'yılan','dis':'diş','kus':'kuş',
}
